# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy all necessary files including package.json, tsconfig.json, and source files
COPY . .

# Install dependencies without running additional scripts
RUN npm install --ignore-scripts

# Build the project
RUN npm run build

# Expose a port if needed (the MCP server communicates over stdio, so this may be optional)
EXPOSE 3000

# Run the MCP server
CMD ["node", "build/index.js"]
