name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fast-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: node build/cli/index.js doctor
      - run: node build/cli/index.js start --stdio --dry-run
      - run: node build/cli/index.js start --http --port 2091 --dry-run
      - name: Security Scan
        run: npm run security-check
